name: cinema-ticket-reservation-development

services:
  cinema-backend:
    build:
      context: ./API
      dockerfile: Dockerfile.dev
    container_name: cinema-backend
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    networks:
      - cinema-ticket-reservation-network

  cinema-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      cinema-backend:
        condition: service_started
    container_name: cinema-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_data:/app/node_modules
    networks:
      - cinema-ticket-reservation-network

  postgres-global:
    image: postgres:16
    container_name: postgres_cinema_global-development
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cinema_db_user
      POSTGRES_PASSWORD: cinema_db_password
      POSTGRES_DB: cinema_db_global
    volumes:
      - postgres_global_data:/var/lib/postgresql/data
    networks:
      - cinema-ticket-reservation-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_cinema-development
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cinema-ticket-reservation-network

networks:
  cinema-ticket-reservation-network:
    driver: bridge

volumes:
  frontend_data:
  postgres_global_data:
  pgadmin_data: