FROM python:3.12.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY poetry.lock pyproject.toml ./
RUN poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

COPY app /app/app
COPY start.sh /start.sh
RUN chmod +x /start.sh


EXPOSE 8000

WORKDIR /app/app

ENTRYPOINT ["/start.sh"]
